import { PrismaClient, Platform } from "@prisma/client";

const prisma = new PrismaClient();

const jobs = [
  {
    title: "Frontend Engineer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    location: "New York, NY",
    locationType: "hybrid",
    salary: "$140K - $200K",
    salaryMin: 140000,
    salaryMax: 200000,
    description: "Build and maintain Stripe's payment UI components using React and TypeScript.",
    requirements: ["3+ years React", "TypeScript expertise", "Performance optimization"],
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    platform: Platform.LINKEDIN,
    platformUrl: "https://linkedin.com/jobs/stripe-frontend",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Software Engineer",
    company: "Vercel",
    companyLogo: "https://logo.clearbit.com/vercel.com",
    location: "New York, NY",
    locationType: "remote",
    salary: "$125K - $180K",
    salaryMin: 125000,
    salaryMax: 180000,
    description: "Work on the Vercel platform, improving build times and developer experience.",
    requirements: ["Node.js", "TypeScript", "Cloud infrastructure"],
    skills: ["React", "TypeScript", "Node.js", "Next.js"],
    platform: Platform.LINKEDIN,
    platformUrl: "https://linkedin.com/jobs/vercel-swe",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Full Stack Engineer",
    company: "Ramp",
    companyLogo: "https://logo.clearbit.com/ramp.com",
    location: "New York, NY",
    locationType: "hybrid",
    salary: "$110K - $160K",
    salaryMin: 110000,
    salaryMax: 160000,
    description: "Build financial tooling and internal products for Ramp's spend management platform.",
    requirements: ["Full stack experience", "Python or Go", "PostgreSQL"],
    skills: ["React", "TypeScript", "Python", "PostgreSQL"],
    platform: Platform.INDEED,
    platformUrl: "https://indeed.com/jobs/ramp-fullstack",
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Frontend Engineer",
    company: "Linear",
    companyLogo: "https://logo.clearbit.com/linear.app",
    location: "New York, NY",
    locationType: "remote",
    salary: "$120K - $170K",
    salaryMin: 120000,
    salaryMax: 170000,
    description: "Build the Linear issue tracker UI - one of the most beloved developer tools.",
    requirements: ["React", "GraphQL", "Performance optimization"],
    skills: ["React", "TypeScript", "GraphQL", "Tailwind CSS"],
    platform: Platform.GLASSDOOR,
    platformUrl: "https://glassdoor.com/jobs/linear-frontend",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Software Engineer",
    company: "Airbnb",
    companyLogo: "https://logo.clearbit.com/airbnb.com",
    location: "New York, NY",
    locationType: "hybrid",
    salary: "$130K - $190K",
    salaryMin: 130000,
    salaryMax: 190000,
    description: "Build scalable web services and APIs for Airbnb's marketplace platform.",
    requirements: ["React or React Native", "TypeScript", "Python or Java"],
    skills: ["React", "TypeScript", "Python", "React Native"],
    platform: Platform.LINKEDIN,
    platformUrl: "https://linkedin.com/jobs/airbnb-swe",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Full Stack Engineer",
    company: "Datadog",
    companyLogo: "https://logo.clearbit.com/datadoghq.com",
    location: "New York, NY",
    locationType: "remote",
    salary: "$125K - $175K",
    salaryMin: 125000,
    salaryMax: 175000,
    description: "Build observability and monitoring features for Datadog's cloud platform.",
    requirements: ["Full stack", "Go or Python", "AWS or GCP"],
    skills: ["React", "TypeScript", "Go", "AWS"],
    platform: Platform.INDEED,
    platformUrl: "https://indeed.com/jobs/datadog-fullstack",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Senior Frontend Engineer",
    company: "Figma",
    companyLogo: "https://logo.clearbit.com/figma.com",
    location: "San Francisco, CA",
    locationType: "hybrid",
    salary: "$160K - $220K",
    salaryMin: 160000,
    salaryMax: 220000,
    description: "Build the next generation of design tools that millions of designers use daily.",
    requirements: ["5+ years frontend", "Canvas/WebGL", "TypeScript"],
    skills: ["TypeScript", "React", "WebGL", "Canvas"],
    platform: Platform.LINKEDIN,
    platformUrl: "https://linkedin.com/jobs/figma-senior-fe",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Backend Engineer",
    company: "Notion",
    companyLogo: "https://logo.clearbit.com/notion.so",
    location: "San Francisco, CA",
    locationType: "remote",
    salary: "$140K - $190K",
    salaryMin: 140000,
    salaryMax: 190000,
    description: "Scale Notion's backend infrastructure to support millions of collaborative users.",
    requirements: ["Node.js or Go", "PostgreSQL", "Distributed systems"],
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis"],
    platform: Platform.GLASSDOOR,
    platformUrl: "https://glassdoor.com/jobs/notion-backend",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];

async function main() {
  console.log("Seeding database...");
  for (const job of jobs) {
    await prisma.job.upsert({
      where: { id: job.company + job.title },
      update: {},
      create: job,
    });
  }
  console.log(`Seeded ${jobs.length} jobs`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
